name: "clang-format Check"
description: "Use clang-format to see if your C/C++ code is formatted according to project guidelines."

branding:
  icon: "check-circle"
  color: "blue"

inputs:
  check-path:
    description: 'The path to the directory you want to check for correct C/C++formatting. Default is the full repository.'
    required: false
    default: '.'

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.check-path }}
