name: stale-image-clean

on:
  schedule:
    - cron: '5 4 * * 5'
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: clang-format

jobs:
  clean-untagged-images:
    name: Clean untagged images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install ghcr-cleaner
        run: go install github.com/jidicula/ghcr-cleaner
      - name: Run ghcr-cleaner
        run: ghcr-cleaner --token "${{ secrets.GITHUB_TOKEN }}" --packagename clang-format
